### PR TITLE
Update 8.2.Dockerfile

### LINKED ISSUE #42: Need apt-get and pdftotext
Hey there, Can we enable the apt-get option into this image, and with that, I can install the library pdftotext ?

### PR DESCRIPTION
**Pull request by Achillesjr**
Add the library for pdftotext (poppler-utils)

closes #42

### CODE REVIEW

**Comment by adhocore** [comment]
👍 thanks. did you get a chance to compare size before and after?

**Comment by Achillesjr** [comment]
According to Alpine, the Installed size is 584 kB.

**Comment by adhocore** [comment]
we may need to add to 8.0 and 8.1 too?

**Comment by Achillesjr** [comment]
I think it’s a good idea.. it’s going to be helpful.

From: Jitendra Adhikari ***@***.***>
Date: Tuesday, October 31, 2023 at 2:38 AM
To: adhocore/docker-lemp ***@***.***>
Cc: Achillesjr ***@***.***>, Author ***@***.***>
Subject: Re: [adhocore/docker-lemp] Update 8.2.Dockerfile (PR #43)

we may need to add to 8.0 and 8.1 too?

**Comment by adhocore** [comment]
hello, could you please update the PR? i plan to merge it asap

**Pull request merged**
